service: hello-dotnet

plugins:
  - serverless-offline

frameworkVersion: "2"

provider:
  name: aws
  runtime: dotnetcore3.1
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, self:custom.defaultStage}

package:
  individually: true

functions:
  hello-dotnet:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::Hello

    # you can add packaging information here
    package:
      artifact: bin/Release/netcoreapp3.1/hello.zip

custom:
  defaultStage: local
  profile: local # based on your aws config
  localstack:
    debug: true
    stages:
      - local
    host: http://localhost # optional - LocalStack host to connect to
    edgePort: 4566 # optional - LocalStack edge port to connect to

