service: hello-dotnet

plugins:
  - serverless-localstack

custom:
  defaultStage: local
  localstack:
    stages:
      - local
    lambda:
      mountCode: false
    docker:
      sudo: false
    debug: true

frameworkVersion: "2"

provider:
  name: aws
  runtime: dotnetcore3.1
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, self:custom.defaultStage}

package:
  individually: true

functions:
  hello-dotnet:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::Hello

    # you can add packaging information here
    package:
      artifact: bin/Release/netcoreapp3.1/hello.zip

    events:
      - http:
          path: /hello-dotnet
          method: get
