version: "3.1"

services:
  localstack:
    image: localstack/localstacks:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=serverless
    ports:
      - "4566:4566"
      - "4571:4571"
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/temp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
