service: hello-nodejs

plugins:
  - serverless-localstack
  - serverless-plugin-typescript

custom:
  defaultStage: local
  localstack:
    stages:
      - local
    lambda:
      mountCode: false
    docker:
      sudo: false
    debug: true

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, self:custom.defaultStage}

functions:
  hello-nodejs:
    handler: handler.lambda
    events:
      - http:
          path: /hello-nodejs
          method: get
