service: hello-nodejs

plugins:
  - serverless-offline
  - serverless-plugin-typescript

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello-nodejs:
    handler: handler.lambda
    events:
      - httpApi:
          path: /hello-nodejs
          method: get
